/**
 * Route Web Merchant — nguồn: design/spec/routes.web.ts (WM-*). Không hard-code URL ở page; dùng PATHS / paths.*.
 */
export const PATHS = {
  login: '/login',
  onboarding: '/onboarding/merchant',
  selectMerchant: '/select-merchant',
  accessPending: '/access-pending',
  dashboard: '/',
  dashboardOperations: '/dashboard/operations',
  dashboardFinance: '/dashboard/finance',
  orders: '/orders',
  orderNew: '/orders/new',
  bookings: '/bookings',
  dispatch: '/dispatch',
  dispatchCalendar: '/dispatch/calendar',
  dispatchConflicts: '/dispatch/conflicts',
  dispatchMap: '/dispatch/map',
  incidents: '/dispatch/incidents',
  finance: '/finance',
  payments: '/finance/payments',
  paymentNew: '/finance/payments/new',
  expenses: '/finance/expenses',
  expenseNew: '/finance/expenses/new',
  customerDebt: '/finance/customer-debt',
  supplierDebt: '/finance/supplier-debt',
  debtStatements: '/finance/debt-statements',
  cod: '/finance/cod',
  tripAdvances: '/finance/trip-advances',
  vehicles: '/vehicles',
  vehicleNew: '/vehicles/new',
  suppliers: '/suppliers',
  supplierNew: '/suppliers/new',
  customers: '/customers',
  customerNew: '/customers/new',
  drivers: '/drivers',
  driverNew: '/drivers/new',
  payroll: '/payroll',
  payrollNew: '/payroll/new',
  reports: '/reports',
  reportProfit: '/reports/profit',
  reportVehicles: '/reports/vehicles',
  reportDrivers: '/reports/drivers',
  reportCustomerDebt: '/reports/customer-debt',
  reportCod: '/reports/cod',
  reportPayroll: '/reports/payroll',
  settingsCompany: '/settings/company',
  settingsUsers: '/settings/users',
  settingsUserNew: '/settings/users/new',
  settingsRoles: '/settings/roles',
  settingsOperations: '/settings/operations',
  settingsNumbering: '/settings/numbering',
  settingsCatalogs: '/settings/catalogs',
  devComponents: '/dev/components',
} as const;

export const paths = {
  order: (id: string, tab?: 'stops' | 'cargo' | 'finance' | 'trips' | 'incidents' | 'attachments' | 'timeline') => `/orders/${id}${tab ? `?tab=${tab}` : ''}`,
  orderEdit: (id: string) => `/orders/${id}/edit`,
  orderPrint: (id: string) => `/orders/${id}/print`,
  orderTripNew: (orderId: string) => `/orders/${orderId}/trips/new`,
  orderStop: (orderId: string, stopId: string) => `/orders/${orderId}/stops/${stopId}`,
  trip: (id: string) => `/trips/${id}`,
  tripEdit: (id: string) => `/trips/${id}/edit`,
  incident: (id: string) => `/dispatch/incidents/${id}`,
  payment: (id: string) => `/finance/payments/${id}`,
  paymentAllocate: (id: string) => `/finance/payments/${id}/allocate`,
  expense: (id: string) => `/finance/expenses/${id}`,
  debtStatement: (id: string) => `/finance/debt-statements/${id}`,
  vehicle: (id: string) => `/vehicles/${id}`,
  vehicleEdit: (id: string) => `/vehicles/${id}/edit`,
  supplier: (id: string) => `/suppliers/${id}`,
  supplierEdit: (id: string) => `/suppliers/${id}/edit`,
  customer: (id: string, tab?: 'debt' | 'orders' | 'locations' | 'attachments' | 'timeline' | 'statements') => `/customers/${id}${tab ? `?tab=${tab}` : ''}`,
  customerEdit: (id: string) => `/customers/${id}/edit`,
  customerLocations: (id: string) => `/customers/${id}/locations`,
  driver: (id: string, tab?: 'ledger' | 'salary' | 'trips' | 'payroll' | 'attachments' | 'timeline') => `/drivers/${id}${tab ? `?tab=${tab}` : ''}`,
  driverCod: (id: string) => `/drivers/${id}?tab=ledger&view=cod`,
  driverEdit: (id: string) => `/drivers/${id}/edit`,
  driverSalaryHistory: (id: string) => `/drivers/${id}/salary-history`,
  payrollDetail: (id: string) => `/payroll/${id}`,
  payrollLine: (payrollId: string, lineId: string) => `/payroll/${payrollId}/lines/${lineId}`,
  payrollApprove: (id: string) => `/payroll/${id}/approve`,
  settingsUser: (id: string) => `/settings/users/${id}`,
  reportProfitOrders: () => '/reports/profit?view=orders',
};

/** Map screen ID → route pattern (đối chiếu design/spec/routes.web.ts). */
export const SCREEN_ROUTES: Record<string, string> = {
  'WM-ORD-01': '/orders',
  'WM-ORD-02': '/orders/:orderId',
  'WM-ORD-03': '/orders/new',
  'WM-ORD-03-EDIT': '/orders/:orderId/edit',
  'WM-ORD-09': '/orders/:orderId/print',
  'WM-AUTH-01': '/login',
  'WM-AUTH-02': '/onboarding/merchant',
  'WM-AUTH-03': '/select-merchant',
  'WM-AUTH-04': '/access-pending',
  'WM-DASH-01': '/',
  'WM-DASH-02': '/dashboard/operations',
  'WM-DASH-03': '/dashboard/finance',
  'WM-TRIP-01': '/trips/:tripId',
  'WM-TRIP-02': '/orders/:orderId/trips/new',
  'WM-TRIP-02-EDIT': '/trips/:tripId/edit',
  'WM-STOP-01': '/orders/:orderId/stops/:stopId',
  'WM-DISPATCH-01': '/dispatch',
  'WM-DISPATCH-02': '/dispatch/calendar',
  'WM-DISPATCH-03': '/dispatch/conflicts',
  'WM-DISPATCH-04': '/dispatch/map',
  'WM-DISPATCH-05': '/dispatch/incidents',
  'WM-INC-01': '/dispatch/incidents/:incidentId',
  'WM-FIN-01': '/finance',
  'WM-PAY-01': '/finance/payments',
  'WM-PAY-02': '/finance/payments/:paymentId',
  'WM-PAY-03': '/finance/payments/new',
  'WM-PAY-04': '/finance/payments/:paymentId/allocate',
  'WM-EXP-01': '/finance/expenses',
  'WM-EXP-02': '/finance/expenses/:expenseId',
  'WM-EXP-03': '/finance/expenses/new',
  'WM-DEBT-01': '/finance/customer-debt',
  'WM-DEBT-02': '/finance/supplier-debt',
  'WM-DEBT-03': '/finance/debt-statements',
  'WM-DEBT-04': '/finance/debt-statements/:statementId',
  'WM-COD-01': '/finance/cod',
  'WM-ADV-01': '/finance/trip-advances',
  'WM-VEH-01': '/vehicles',
  'WM-VEH-02': '/vehicles/:vehicleId',
  'WM-VEH-03': '/vehicles/new',
  'WM-VEH-03-EDIT': '/vehicles/:vehicleId/edit',
  'WM-SUP-01': '/suppliers',
  'WM-SUP-02': '/suppliers/:supplierId',
  'WM-SUP-03': '/suppliers/new',
  'WM-SUP-03-EDIT': '/suppliers/:supplierId/edit',
  'WM-CUS-01': '/customers',
  'WM-CUS-02': '/customers/:customerId',
  'WM-CUS-03': '/customers/new',
  'WM-CUS-03-EDIT': '/customers/:customerId/edit',
  'WM-CUS-04': '/customers/:customerId/locations',
  'WM-DRV-01': '/drivers',
  'WM-DRV-02': '/drivers/:driverId',
  'WM-DRV-03': '/drivers/new',
  'WM-DRV-03-EDIT': '/drivers/:driverId/edit',
  'WM-DRV-04': '/drivers/:driverId/salary-history',
  'WM-PAYROLL-01': '/payroll',
  'WM-PAYROLL-02': '/payroll/:payrollId',
  'WM-PAYROLL-03': '/payroll/new',
  'WM-PAYROLL-04': '/payroll/:payrollId/lines/:lineId',
  'WM-PAYROLL-05': '/payroll/:payrollId/approve',
  'WM-RPT-01': '/reports',
  'WM-RPT-02': '/reports/profit',
  'WM-RPT-04': '/reports/vehicles',
  'WM-RPT-05': '/reports/drivers',
  'WM-RPT-06': '/reports/customer-debt',
  'WM-RPT-07': '/reports/cod',
  'WM-RPT-08': '/reports/payroll',
  'WM-ORG-01': '/settings/company',
  'WM-USER-01': '/settings/users',
  'WM-USER-02': '/settings/users/:userId',
  'WM-USER-03': '/settings/users/new',
  'WM-RBAC-01': '/settings/roles',
  'WM-SET-01': '/settings/operations',
  'WM-SET-02': '/settings/numbering',
  'WM-CAT-01': '/settings/catalogs',
};
