"""Business flows (doc/2-PRD/06-ui-flow-specs.md + 01-danh-sach-man-hinh.md §7).
step = (actor, screen_id, action). screen_id may be None for pure system/API steps.
"""

FLOWS = [
    {"id": "FLOW-AUTH-MERCHANT", "name": "Đăng nhập & onboarding merchant", "source": "06-ui-flow-specs §2",
     "steps": [("User", "WM-AUTH-01", "Bấm Đăng nhập bằng Google"),
               ("System", None, "Firebase ID token → verify, tra membership"),
               ("System", "WM-DASH-01", "4a. Đúng 1 merchant → vào Dashboard"),
               ("System", "WM-AUTH-03", "4b. Nhiều merchant → chọn nhà xe"),
               ("System", "WM-AUTH-04", "4c. Chưa thuộc merchant → chờ mời / tạo mới"),
               ("User", "WM-AUTH-02", "Nhập thông tin doanh nghiệp → tạo merchant, seed danh mục"),
               ("System", "WM-DASH-01", "Mở Dashboard")]},
    {"id": "FLOW-MASTER-DATA", "name": "CRUD dữ liệu nền (khách, tài xế, xe, NCC)", "source": "06-ui-flow-specs §3",
     "steps": [("User", "WM-CUS-01", "Tìm/lọc, bấm Tạo"), ("User", "WM-CUS-03", "Nhập field bắt buộc, lưu"),
               ("System", "WM-CUS-02", "Mở chi tiết vừa tạo"), ("User", "WM-CUS-04", "Thêm địa chỉ/liên hệ"),
               ("User", "WM-DRV-03", "Tạo tài xế + tài khoản app"), ("User", "WM-DRV-04", "Thêm mốc lương cố định"),
               ("User", "WM-VEH-03", "Tạo xe (biển số duy nhất)"), ("User", "WM-SUP-03", "Tạo NCC"),
               ("User", "WM-SHELL-04", "Hoặc import Excel")]},
    {"id": "FLOW-ORDER-ONE-TRUCK", "name": "Tạo đơn 1 xe nhanh → điều phối → tài xế", "source": "06-ui-flow-specs §4, 01 §7.1",
     "steps": [("Operation", "WM-ORD-01", "Bấm Tạo đơn"),
               ("Operation", "WM-ORD-03", "Chọn khách, điểm lấy/trả từ sổ địa chỉ, hàng, giá cước, add-on, hạn TT"),
               ("System", "WM-ORD-02", "Tạo mã DH, mở chi tiết đơn"),
               ("Operation", "WM-TRIP-02", "Tạo chuyến: chọn xe, tài xế, giờ; mặc định gán mọi điểm"),
               ("System", "WM-DISPATCH-03", "Cảnh báo trùng/gần trùng lịch (mềm) → override kèm lý do"),
               ("System", "WM-DISPATCH-01", "Chuyến xuất hiện trên bảng điều phối"),
               ("Driver", "DA-HOME-01", "Tài xế thấy chuyến được giao")]},
    {"id": "FLOW-ORDER-MULTI-TRUCK", "name": "Đơn nhiều xe", "source": "06-ui-flow-specs §5",
     "steps": [("Operation", "WM-ORD-03", "Tạo đơn với toàn bộ điểm, hàng, giá cước tổng"),
               ("Operation", "WM-ORD-02", "Mở tab Chuyến"),
               ("Operation", "WM-TRIP-02", "Tạo chuyến A: chọn tập điểm"),
               ("Operation", "WM-TRIP-02", "Tạo chuyến B: điểm còn lại"),
               ("System", "WM-ORD-04", "Tab Điểm dừng cho thấy điểm nào thuộc chuyến nào"),
               ("Operation", "WM-DISPATCH-02", "Kiểm tra lịch xe/tài xế")]},
    {"id": "FLOW-DRIVER-FIELD", "name": "Tài xế: trạng thái, POD, COD (có offline)", "source": "06-ui-flow-specs §6",
     "steps": [("Driver", "DA-HOME-01", "Mở chuyến đang chạy"), ("Driver", "DA-TRIP-01", "Xem điểm, hàng, ghi chú, COD"),
               ("Driver", "DA-STATUS-01", "Cập nhật: Đang đến điểm lấy"), ("Driver", "DA-STOP-02", "Đã đến / hoàn thành điểm lấy"),
               ("Driver", "DA-STATUS-01", "Đang vận chuyển → Đang trả hàng"), ("Driver", "DA-COD-01", "Nhập COD thực thu"),
               ("Driver", "DA-POD-01", "Chụp POD"), ("Driver", "DA-STOP-02", "Hoàn thành điểm trả"),
               ("Driver", "DA-SYNC-01", "Offline: hàng đợi, thử lại"),
               ("Operation", "WM-TRIP-01", "Thấy trạng thái, POD, COD")]},
    {"id": "FLOW-PAUSE-INCIDENT", "name": "Tạm dừng chuyến & báo sự cố", "source": "03-driver-app-ui §10, 01 §3.9",
     "steps": [("Driver", "DA-TRIP-01", "Mở chuyến"), ("Driver", "DA-STATUS-02", "Tạm dừng: chọn lý do (giờ cấm tải, nghỉ đêm…)"),
               ("Driver", "DA-INC-01", "Báo sự cố: loại, mức độ, mô tả, ảnh (lưu offline được)"),
               ("Operation", "WM-DISPATCH-05", "Sự cố xuất hiện trong danh sách"),
               ("Operation", "WM-INC-01", "Gán người xử lý, cập nhật, đóng sự cố")]},
    {"id": "FLOW-PAYMENT-ALLOCATION", "name": "Khách thanh toán & phân bổ", "source": "06-ui-flow-specs §7, 01 §7.2",
     "steps": [("Accountant", "WM-DEBT-01", "Mở công nợ khách"), ("Accountant", "WM-CUS-05", "Hoặc từ tab công nợ khách"),
               ("Accountant", "WM-PAY-03", "Tạo phiếu thu loại Khách trả"), ("System", "WM-PAY-02", "Phiếu thu hiện số chưa phân bổ"),
               ("Accountant", "WM-PAY-04", "Phân bổ vào các đơn còn nợ; dư → số dư khách"),
               ("System", "WM-CUS-05", "Cập nhật công nợ và số dư")]},
    {"id": "FLOW-COD-REMITTANCE", "name": "COD tài xế: thu tại điểm → nộp lại", "source": "06-ui-flow-specs §8, 01 §7.3",
     "steps": [("Driver", "DA-COD-01", "Nhập COD thực thu tại điểm trả"), ("System", "WM-COD-01", "COD đang giữ hiện theo tài xế"),
               ("Accountant", "WM-COD-01", "Chọn khoản COD cần nộp"),
               ("Accountant", "WM-PAY-03", "Tạo phiếu thu loại Tài xế nộp COD (không phải doanh thu)"),
               ("System", "WM-DRV-05", "Sổ công nợ tài xế cập nhật")]},
    {"id": "FLOW-EXPENSE-PROFIT", "name": "Chi phí, tạm ứng & lãi/lỗ đơn", "source": "01 §7.4",
     "steps": [("Operation", "WM-EXP-03", "Tạo phiếu chi, gắn đơn/chuyến/xe/NCC/tài xế"),
               ("System", "WM-EXP-02", "Chi tiết phiếu chi"), ("Operation", "WM-ADV-01", "Đối soát tạm ứng chuyến"),
               ("System", "WM-ORD-07", "Lãi/lỗ đơn cập nhật"), ("Admin", "WM-RPT-03", "Báo cáo lãi/lỗ theo đơn")]},
    {"id": "FLOW-DEBT-STATEMENT", "name": "Chốt bảng kê công nợ", "source": "06-ui-flow-specs §9",
     "steps": [("Accountant", "WM-DEBT-01", "Lọc khách/kỳ"), ("Accountant", "WM-DEBT-03", "Tạo bảng kê"),
               ("System", "WM-DEBT-04", "Xem trước dòng bảng kê"), ("Accountant", "WM-DEBT-04", "Chốt → snapshot + PDF"),
               ("Accountant", "WM-SHELL-05", "Tải/chia sẻ PDF"), ("Customer", "CW-DEBT-01", "Khách tải bảng kê đã gửi (phase 3)")]},
    {"id": "FLOW-PAYROLL", "name": "Tạo & duyệt bảng lương", "source": "06-ui-flow-specs §10, 01 §7.5",
     "steps": [("Operation", "WM-PAYROLL-03", "Chọn kỳ lương → sinh dòng lương"), ("Operation", "WM-PAYROLL-02", "Kiểm tra bảng lương"),
               ("Operation", "WM-PAYROLL-04", "Thêm giảm trừ (có lý do)"), ("Operation", "WM-PAYROLL-02", "Gửi duyệt"),
               ("Admin", "WM-PAYROLL-05", "Giám đốc duyệt / trả về"), ("Admin", "MA-PAYROLL-01", "Hoặc duyệt trên App Merchant"),
               ("Accountant", "WM-SHELL-05", "Xuất bảng lương"), ("Driver", "DA-MONEY-01", "Tài xế xem thưởng/ứng")]},
    {"id": "FLOW-BOOKING-CUSTOMER", "name": "Booking khách hàng → đơn (phase 3)", "source": "06-ui-flow-specs §11, 01 §7.6",
     "steps": [("Customer", "CW-HOME-01", "Tìm nhà xe"), ("Customer", "CW-MER-01", "Xem hồ sơ nhà xe"),
               ("Customer", "CW-BOOK-01", "Gửi yêu cầu vận chuyển"), ("System", "CW-BOOK-03", "Booking chờ tiếp nhận"),
               ("Operation", "WM-ORD-03", "Tiếp nhận, chỉnh giá/điểm/hàng → tạo đơn"),
               ("Customer", "CW-ORD-02", "Khách theo dõi đơn đã tạo")]},
    {"id": "FLOW-MERCHANT-MOBILE", "name": "App Merchant: theo dõi & duyệt nhanh (phase 2)", "source": "01 §5",
     "steps": [("Admin", "MA-HOME-01", "Mở tổng quan mobile"), ("Admin", "MA-TRIP-02", "Xem chuyến, gọi tài xế"),
               ("Admin", "MA-COD-01", "Xem COD tài xế đang giữ"), ("Admin", "MA-PAYROLL-01", "Duyệt bảng lương"),
               ("Operation", "MA-ORD-03", "Tạo nhanh đơn, chi tiết chỉnh trên web")]},
]
