#!/usr/bin/env python3
"""Generate tokens.css (CSS vars + shadcn vars), tailwind.preset.cjs and bta_tokens.dart from design/tokens/tokens.json."""
import json
import os

D = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "tokens")
t = json.load(open(os.path.join(D, "tokens.json"), encoding="utf-8"))
colors = {c["name"]: c["value"] for c in t["color"]["tokens"]}
colors["ring"] = colors["primary"]
styles = [s for g in t["type"]["groups"] for s in g["styles"]]


def rgb(h):
    h = h.lstrip("#")
    return f"{int(h[0:2], 16)} {int(h[2:4], 16)} {int(h[4:6], 16)}"


def camel(n):
    p = n.split("-")
    return p[0] + "".join(x.title() for x in p[1:])


css = ["/* BTA design tokens — generated by design/tools/gen_tokens.py from tokens.json (design system BTA). */", ":root {"]
css += [f"  --bta-{k}: {v};" for k, v in colors.items()]
css.append(f"  --bta-font-sans: {t['type']['families']['sans']};")
css.append(f"  --bta-font-mono: {t['type']['families']['mono']};")
css += [f"  --bta-font-{s['name']}: {s['fontWeight']} {s['fontSize']}/{s['lineHeight']} var(--bta-font-sans);" for s in styles]
for grp in ("spacing", "radius", "shadow", "size"):
    css += [f"  --bta-{s['name']}: {s['value']};" for s in t[grp]["tokens"]]
css += ["", "  /* shadcn/ui variables (space-separated RGB for Tailwind <alpha-value>) */"]
m = {"background": "background", "foreground": "text", "card": "surface", "card-foreground": "text", "popover": "surface",
     "popover-foreground": "text", "muted": "surface-muted", "muted-foreground": "text-muted", "border": "border", "input": "border-control",
     "primary": "primary", "primary-foreground": "primary-foreground", "secondary": "surface-muted", "secondary-foreground": "text",
     "accent": "accent-soft", "accent-foreground": "accent", "destructive": "danger", "destructive-foreground": "primary-foreground", "ring": "primary"}
css += [f"  --{k}: {rgb(colors[v])};" for k, v in m.items()]
css += ["  --radius: 8px;", "}", "",
        "html { font-family: var(--bta-font-sans); color: var(--bta-text); background: var(--bta-background); }",
        ".tabular, td.num, .money { font-variant-numeric: tabular-nums; }",
        ":focus-visible { outline: 2px solid var(--bta-ring); outline-offset: 2px; }", ""]
open(os.path.join(D, "tokens.css"), "w", encoding="utf-8").write("\n".join(css))

tw = ["// Tailwind preset — generated by design/tools/gen_tokens.py. apps/web: presets: [require('../../design/tokens/tailwind.preset.cjs')]",
      "module.exports = {", "  theme: {", "    extend: {", "      colors: {"]
tw += [f"        '{k}': 'var(--bta-{k})'," for k in colors]
tw += ["      },", "      fontFamily: { sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', '\"Segoe UI\"', 'sans-serif'] },", "      fontSize: {"]
tw += [f"        '{s['name']}': ['{s['fontSize']}', {{ lineHeight: '{s['lineHeight']}', fontWeight: '{s['fontWeight']}' }}]," for s in styles]
tw += ["      },",
       "      spacing: { " + ", ".join(f"'{s['name'].replace('space-', '')}': '{s['value']}'" for s in t["spacing"]["tokens"]) + " },",
       "      borderRadius: { sm: '4px', md: '6px', lg: '8px' },",
       "      boxShadow: { " + ", ".join(f"'{s['name'].replace('shadow-', '')}': '{s['value']}'" for s in t["shadow"]["tokens"]) + " },",
       "      width: { sidebar: '260px', 'drawer-sm': '480px', 'drawer-lg': '720px' },",
       "      height: { topbar: '56px', row: '44px', control: '36px', tap: '48px' },",
       "    },", "  },", "};", ""]
open(os.path.join(D, "tailwind.preset.cjs"), "w", encoding="utf-8").write("\n".join(tw))

d = ["// BTA design tokens for Flutter (apps/driver-app, merchant app) — generated by design/tools/gen_tokens.py.",
     "import 'dart:ui' show FontFeature;", "import 'package:flutter/material.dart';", "", "class BtaColors {", "  BtaColors._();"]
d += [f"  static const {camel(k)} = Color(0xFF{v.lstrip('#').upper()});" for k, v in colors.items()]
d += ["}", "", "class BtaSpace {", "  BtaSpace._();"]
d += [f"  static const double s{s['name'].split('-')[1]} = {s['value'].replace('px', '')};" for s in t["spacing"]["tokens"]]
d += ["}", "", "class BtaRadius {", "  BtaRadius._();", "  static const double sm = 4;", "  static const double md = 6;", "  static const double lg = 8;", "}", "",
      "class BtaSize {", "  BtaSize._();", "  static const double tapTarget = 48;", "  static const double controlHeight = 36;", "}", "",
      "class BtaText {", "  BtaText._();", "  static const _f = 'Inter';"]
for s in styles:
    fs = float(s["fontSize"].replace("px", ""))
    lh = float(s["lineHeight"].replace("px", ""))
    d.append(f"  static const {camel(s['name'])} = TextStyle(fontFamily: _f, fontSize: {fs:g}, height: {lh / fs:.3f}, fontWeight: FontWeight.w{s['fontWeight']});")
d += ["  /// Driver app: key data (address, contact, COD, status) one step above body.",
      "  static const mobileKey = TextStyle(fontFamily: _f, fontSize: 16, height: 1.5, fontWeight: FontWeight.w600);",
      "  static const tabular = [FontFeature.tabularFigures()];", "}", "",
      "ThemeData btaTheme() => ThemeData(", "  useMaterial3: true,", "  fontFamily: 'Inter',", "  scaffoldBackgroundColor: BtaColors.background,",
      "  colorScheme: const ColorScheme.light(", "    primary: BtaColors.primary,", "    onPrimary: BtaColors.primaryForeground,",
      "    secondary: BtaColors.accent,", "    error: BtaColors.danger,", "    surface: BtaColors.surface,", "    onSurface: BtaColors.text,",
      "    outline: BtaColors.borderControl,", "  ),", "  dividerColor: BtaColors.border,",
      "  filledButtonTheme: FilledButtonThemeData(style: FilledButton.styleFrom(minimumSize: const Size.fromHeight(BtaSize.tapTarget), "
      "shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(BtaRadius.md)))),",
      "  outlinedButtonTheme: OutlinedButtonThemeData(style: OutlinedButton.styleFrom(minimumSize: const Size(0, BtaSize.tapTarget), "
      "side: const BorderSide(color: BtaColors.borderControl), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(BtaRadius.md)))),",
      "  inputDecorationTheme: const InputDecorationTheme(border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(BtaRadius.sm)), "
      "borderSide: BorderSide(color: BtaColors.borderControl))),", ");", ""]
open(os.path.join(D, "bta_tokens.dart"), "w", encoding="utf-8").write("\n".join(d))
print("tokens generated")
