// BTA design tokens for Flutter (apps/driver-app, merchant app) — generated by design/tools/gen_tokens.py.
import 'dart:ui' show FontFeature;
import 'package:flutter/material.dart';

class BtaColors {
  BtaColors._();
  static const background = Color(0xFFF7F8FA);
  static const surface = Color(0xFFFFFFFF);
  static const surfaceMuted = Color(0xFFF1F4F7);
  static const border = Color(0xFFDDE3EA);
  static const borderStrong = Color(0xFFC3CCD6);
  static const borderControl = Color(0xFF828D99);
  static const text = Color(0xFF17202A);
  static const textMuted = Color(0xFF5B6673);
  static const textSubtle = Color(0xFF66717D);
  static const primary = Color(0xFF0F766E);
  static const primaryHover = Color(0xFF115E59);
  static const primaryForeground = Color(0xFFFFFFFF);
  static const accent = Color(0xFF2563EB);
  static const success = Color(0xFF15803D);
  static const warning = Color(0xFFB45309);
  static const danger = Color(0xFFB91C1C);
  static const info = Color(0xFF1D4ED8);
  static const ring = Color(0xFF0F766E);
  static const dangerHover = Color(0xFF991B1B);
  static const neutralSoft = Color(0xFFEEF1F4);
  static const primarySoft = Color(0xFFE6F3F1);
  static const accentSoft = Color(0xFFEEF3FE);
  static const successSoft = Color(0xFFEDF7F0);
  static const warningSoft = Color(0xFFFEF5EB);
  static const dangerSoft = Color(0xFFFBEAEA);
  static const infoSoft = Color(0xFFE8EEFB);
  static const chart1 = Color(0xFF0D9488);
  static const chart2 = Color(0xFF2A78D6);
  static const chart3 = Color(0xFFEB6834);
  static const chart4 = Color(0xFF4A3AA7);
}

class BtaSpace {
  BtaSpace._();
  static const double s1 = 4;
  static const double s2 = 8;
  static const double s3 = 12;
  static const double s4 = 16;
  static const double s5 = 20;
  static const double s6 = 24;
  static const double s8 = 32;
}

class BtaRadius {
  BtaRadius._();
  static const double sm = 4;
  static const double md = 6;
  static const double lg = 8;
}

class BtaSize {
  BtaSize._();
  static const double tapTarget = 48;
  static const double controlHeight = 36;
}

class BtaText {
  BtaText._();
  static const _f = 'Inter';
  static const displaySm = TextStyle(fontFamily: _f, fontSize: 24, height: 1.333, fontWeight: FontWeight.w600);
  static const headingLg = TextStyle(fontFamily: _f, fontSize: 20, height: 1.400, fontWeight: FontWeight.w600);
  static const headingMd = TextStyle(fontFamily: _f, fontSize: 18, height: 1.444, fontWeight: FontWeight.w600);
  static const headingSm = TextStyle(fontFamily: _f, fontSize: 16, height: 1.500, fontWeight: FontWeight.w600);
  static const body = TextStyle(fontFamily: _f, fontSize: 14, height: 1.571, fontWeight: FontWeight.w400);
  static const bodyStrong = TextStyle(fontFamily: _f, fontSize: 14, height: 1.571, fontWeight: FontWeight.w600);
  static const bodySm = TextStyle(fontFamily: _f, fontSize: 13, height: 1.538, fontWeight: FontWeight.w400);
  static const caption = TextStyle(fontFamily: _f, fontSize: 12, height: 1.500, fontWeight: FontWeight.w500);
  /// Driver app: key data (address, contact, COD, status) one step above body.
  static const mobileKey = TextStyle(fontFamily: _f, fontSize: 16, height: 1.5, fontWeight: FontWeight.w600);
  static const tabular = [FontFeature.tabularFigures()];
}

ThemeData btaTheme() => ThemeData(
  useMaterial3: true,
  fontFamily: 'Inter',
  scaffoldBackgroundColor: BtaColors.background,
  colorScheme: const ColorScheme.light(
    primary: BtaColors.primary,
    onPrimary: BtaColors.primaryForeground,
    secondary: BtaColors.accent,
    error: BtaColors.danger,
    surface: BtaColors.surface,
    onSurface: BtaColors.text,
    outline: BtaColors.borderControl,
  ),
  dividerColor: BtaColors.border,
  filledButtonTheme: FilledButtonThemeData(style: FilledButton.styleFrom(minimumSize: const Size.fromHeight(BtaSize.tapTarget), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(BtaRadius.md)))),
  outlinedButtonTheme: OutlinedButtonThemeData(style: OutlinedButton.styleFrom(minimumSize: const Size(0, BtaSize.tapTarget), side: const BorderSide(color: BtaColors.borderControl), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(BtaRadius.md)))),
  inputDecorationTheme: const InputDecorationTheme(border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(BtaRadius.sm)), borderSide: BorderSide(color: BtaColors.borderControl))),
);
