// Generated by design/tools/build.py — screen id -> route name. Do not edit by hand.
class BtaRoutes {
  static const da_auth_01 = 'DriverSplashRoute';
  static const da_auth_02 = 'DriverLoginRoute';
  static const da_auth_03 = 'DriverForgotPasswordRoute';
  static const da_home_01 = 'DriverHomeRoute';
  static const da_job_01 = 'DriverJobListRoute';
  static const da_job_02 = 'DriverJobCalendarRoute';
  static const da_trip_01 = 'DriverTripDetailRoute(tripId)';
  static const da_stop_01 = 'DriverStopListRoute(tripId)';
  static const da_stop_02 = 'DriverStopDetailRoute(stopId)';
  static const da_status_01 = 'DriverStatusUpdateRoute(tripId)';
  static const da_status_02 = 'DriverPauseTripRoute(tripId)';
  static const da_pod_01 = 'DriverPodCaptureRoute(stopId)';
  static const da_cod_01 = 'DriverCodInputRoute(stopId)';
  static const da_inc_01 = 'DriverIncidentReportRoute(tripId)';
  static const da_att_01 = 'DriverAttachmentUploadRoute(entity)';
  static const da_gps_01 = 'DriverGpsPermissionRoute';
  static const da_sync_01 = 'DriverSyncRoute';
  static const da_noti_01 = 'DriverNotificationsRoute';
  static const da_money_01 = 'DriverMoneyRoute';
  static const da_hist_01 = 'DriverHistoryRoute';
  static const da_profile_01 = 'DriverProfileRoute';
}
