// Generated by design/tools/build.py — screen id -> route. Do not edit by hand.
export const WEB_ROUTES = {
  'WM-TRIP-01': '/trips/:tripId',
  'WM-TRIP-02': '/orders/:orderId/trips/new',
  'WM-STOP-01': '/orders/:orderId/stops/:stopId',
  'WM-DISPATCH-01': '/dispatch',
  'WM-DISPATCH-02': '/dispatch/calendar',
  'WM-DISPATCH-03': '/dispatch/conflicts',
  'WM-DISPATCH-04': '/dispatch/map',
  'WM-DISPATCH-05': '/dispatch/incidents',
  'WM-INC-01': '/dispatch/incidents/:incidentId',
  'WM-VEH-01': '/vehicles',
  'WM-VEH-02': '/vehicles/:vehicleId',
  'WM-VEH-03': '/vehicles/new',
  'WM-SUP-01': '/suppliers',
  'WM-SUP-02': '/suppliers/:supplierId',
  'WM-SUP-03': '/suppliers/new',
} as const;
