// Generated by design/tools/build.py — screen id -> route. Do not edit by hand.
export const WEB_ROUTES = {
  'WM-FIN-01': '/finance',
  'WM-PAY-01': '/finance/payments',
  'WM-PAY-02': '/finance/payments/:paymentId',
  'WM-PAY-03': '/finance/payments/new',
  'WM-PAY-04': '/finance/payments/:paymentId/allocate',
  'WM-EXP-01': '/finance/expenses',
  'WM-EXP-02': '/finance/expenses/:expenseId',
  'WM-EXP-03': '/finance/expenses/new',
  'WM-DEBT-01': '/finance/customer-debt',
  'WM-DEBT-02': '/finance/supplier-debt',
  'WM-DEBT-03': '/finance/debt-statements',
  'WM-DEBT-04': '/finance/debt-statements/:statementId',
  'WM-COD-01': '/finance/cod',
  'WM-ADV-01': '/finance/trip-advances',
} as const;
