// Generated by design/tools/build.py — screen id -> route. Do not edit by hand.
export const WEB_ROUTES = {
  'WM-CUS-01': '/customers',
  'WM-CUS-02': '/customers/:customerId',
  'WM-CUS-03': '/customers/new',
  'WM-CUS-04': '/customers/:customerId/locations',
  'WM-CUS-05': '/customers/:customerId?tab=debt',
  'WM-CUS-06': '/customers/:customerId?tab=orders',
  'WM-DRV-01': '/drivers',
  'WM-DRV-02': '/drivers/:driverId',
  'WM-DRV-03': '/drivers/new',
  'WM-DRV-04': '/drivers/:driverId/salary-history',
  'WM-DRV-05': '/drivers/:driverId?tab=ledger',
  'WM-DRV-06': '/drivers/:driverId?tab=ledger&view=cod',
} as const;
